name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1afdc2c6ab5e004ecec40cf24efdbcc22123dd8b307c6810b2001f304c05be9a"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
