name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7aeab0f7b18e12c29481a93fbdeeedfe5ff7f788edad399e9482cc780c4734a"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
