name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9a058c4a7197c22e9df6eabcf6b0dadcaa8e11e1dab28935e00a0ae8fa01f83"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
