name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aeee571d991003fd34f70b913822b4bbdb6c3c8deda87dfd3c9d12df4b007ce"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
