name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a07ae8d244d443a3152a4ea99803f8fcfd8c6e01ff95defefed183ab75dd422"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
