name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0fae07a4cf96bbacac6682eff4542dbefa91839e79eaabe71f136f44797f0e1"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
