name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "541775d5fc549d32bcc92fceb370bb7a2fd31e45b2d9e8abe765ad6eee8687e6"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
