name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8bfdb97ef429dfd810904798d4e50de063ba0fddbcb5d66a5326db6af2d1dd7"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
