name = "Advanced Solar Panels"
filename = "Advanced Solar Panels-4.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2652/182/Advanced Solar Panels-4.3.0.jar"
hash-format = "murmur2"
hash = "869481068"

[update]
[update.curseforge]
file-id = 2652182
project-id = 252714
release-channel = "beta"
