name = "AmbientSounds 3"
filename = "AmbientSounds_v3.0.16_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3089/688/AmbientSounds_v3.0.16_mc1.12.2.jar"
hash-format = "murmur2"
hash = "1304879136"

[update]
[update.curseforge]
file-id = 3089688
project-id = 254284
release-channel = "beta"
