name = "AtomicStryker's Battle Towers"
filename = "BattleTowers-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2817/288/BattleTowers-1.12.2.jar"
hash-format = "murmur2"
hash = "1751242918"

[update]
[update.curseforge]
file-id = 2817288
project-id = 227877
release-channel = "beta"
