name = "Bookshelf"
filename = "Bookshelf-1.16.1-6.1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3020/291/Bookshelf-1.16.1-6.1.12.jar"
hash-format = "murmur2"
hash = "915022683"

[update]
[update.curseforge]
file-id = 3020291
project-id = 228525
release-channel = "beta"
