name = "Gravitation Suite"
filename = "Gravitation Suite-3.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2700/845/Gravitation Suite-3.1.1.jar"
hash-format = "murmur2"
hash = "1763016778"

[update]
[update.curseforge]
file-id = 2700845
project-id = 253590
release-channel = "beta"
