name = "Less Lag"
filename = "lesslag-1.0-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2537/249/lesslag-1.0-1.12.2.jar"
hash-format = "murmur2"
hash = "2596342668"

[update]
[update.curseforge]
file-id = 2537249
project-id = 289444
release-channel = "beta"
