name = "More Planets - Galacticraft Add-on"
filename = "More-Planets-1.12.2-2.1.14-GC261.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3051/422/More-Planets-1.12.2-2.1.14-GC261.jar"
hash-format = "murmur2"
hash = "4134711365"

[update]
[update.curseforge]
file-id = 3051422
project-id = 261990
release-channel = "beta"
