name = "Myst Library"
filename = "mystlibrary-1.12.2-0.0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/924/mystlibrary-1.12.2-0.0.3.0.jar"
hash-format = "murmur2"
hash = "1803709641"

[update]
[update.curseforge]
file-id = 2959924
project-id = 344701
release-channel = "beta"
