name = "Open Modular Passive Defense"
filename = "ompd-1.12.2-3.1.1-76.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3085/585/ompd-1.12.2-3.1.1-76.jar"
hash-format = "murmur2"
hash = "755388743"

[update]
[update.curseforge]
file-id = 3085585
project-id = 254332
release-channel = "beta"
