name = "Ore Excavation Integration"
filename = "oeintegration-2.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2617/198/oeintegration-2.3.4.jar"
hash-format = "murmur2"
hash = "2402055738"

[update]
[update.curseforge]
file-id = 2617198
project-id = 270305
release-channel = "beta"
