name = "Sound Filters"
filename = "SoundFilters-0.12.1_for_1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3025/806/SoundFilters-0.12.1_for_1.12.jar"
hash-format = "murmur2"
hash = "3515647174"

[update]
[update.curseforge]
file-id = 3025806
project-id = 222789
release-channel = "beta"
