name = "TickCentral"
filename = "TickCentral-3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3113/378/TickCentral-3.1.jar"
hash-format = "murmur2"
hash = "1292934890"

[update]
[update.curseforge]
file-id = 3113378
project-id = 377201
release-channel = "beta"
