name = "Tiquality"
filename = "Tiquality-THIN-1.12.2-GAMMA-1.8.1-124.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2910/931/Tiquality-THIN-1.12.2-GAMMA-1.8.1-124.jar"
hash-format = "murmur2"
hash = "3002722402"

[update]
[update.curseforge]
file-id = 2910931
project-id = 301913
release-channel = "beta"
